version: '3.5'

services:

  producer:
    build:
      context: .
      dockerfile: Producer.Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - 5001:80

  consumer:
    build:
      context: .
      dockerfile: Consumer.Dockerfile
    restart: always
    depends_on:
      - producer
      - rabbitmq

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    expose:
      - "5672"
      - "15672"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
